### PR TITLE
#167457194 Users Should Be Able To Delete Their Comment And Fetch All Comments

### PR DESCRIPTION
**Pull request by kodek-sleuth**
#### What does this PR do?
Should enable a user to get and delete comments
#### Description of Task to be completed
- Create a controller for comments
- Add delete and get methods to handle the functionality
#### How should this be manually tested?

1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-access-level-control-167457194
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgres://username:password@localhost:5432/authorshaven
DATABASE_=postgres://username:password@localhost:5432/testing-ah
SECRET=whatever you want it to be
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Install and setup Postman to consume CRUD endpoints
6. Run the following requests in Postman using `localhost:3000`
## Endpoints
|  Method  |  Endpoint  |  Task  |
|  --- |  --- |  ---  |
|  `GET`  |  `/api/articles/:slug/comments`  |  `fetches all comments of specific article`  |
|  `GET`  |  `/api/articles/feed`  |  `fetches all comments of an article`  |
|  `DELETE`  |  `/api/comments/commentId`  |  `deletes a comment`  |
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167457194](https://www.pivotaltracker.com/story/show/167457194)

#### Screenshots (if appropriate)
Screen Shot 2019-07-30 at 10 12 09
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by Hervera — CHANGES_REQUESTED** [review]
Increase the coverage

**Review by IsaiahRn — DISMISSED** [review]
It is ready to be merged!

**Review by Hervera — CHANGES_REQUESTED** [review]
Ready to be merged

**Review by niyoceles — DISMISSED** [review]

**Review by Hervera — DISMISSED** [review]

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
kindly correct `What are the relevant pivotal tracker stories?`

**Review by Hervera — DISMISSED** [review]
Ready to be merged

**Review by niyoceles — DISMISSED** [review]

**Review by IsaiahRn — DISMISSED** [review]

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by niyoceles — APPROVED** [review]

**Review by IsaiahRn — APPROVED** [review]

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Pull request merged**
