### PR TITLE
#166790005 Users Should Be Able to Receive Notifications

### PR DESCRIPTION
**Pull request by elemanhillary-zz**
#### What does this PR do?
- Adds push and e-mail notifications functionality 
- Adds opt-in or opt-out notification system.

#### Description of Task to be completed
- user should be notified when users he/she follow publish new articles.
- user should be notified when articles I favorited have new comments or likes.
- user should be able to opt-in or opt-out of the notification system.

#### How should this be manually tested?
```bash
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-notifications-functionality-166790005
npm install
npm run dev
```

- `localhost:3000/api/notifications/subscribe` subscribe to email notifications
- follow an author `localhost:3000/api/<author-name>/follow` OR
- like or favourite an article `localhost:3000/api/favorite/<slug>`

#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
[#166790005](https://www.pivotaltracker.com/story/show/166790005)

#### Screenshots (if appropriate)
Imgur

#### Checklist
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by niyoceles — CHANGES_REQUESTED** [review]
Could you please add the screenshots of your postman.

**Review by IsaiahRn — COMMENTED** [review]
Some screenshots would be helpful

**Comment by niyoceles** [comment]
> Some screenshots would be helpful

Exactly.

**Review by Hervera — DISMISSED** [review]
Ready to be approved

**Review by niyoceles — APPROVED** [review]

**Review by IsaiahRn — APPROVED** [review]

**Review by Hervera — APPROVED** [review]

**Pull request merged**
