### PR TITLE
Fix Bug On User Follow Each Other

### PR DESCRIPTION
**Pull request by niyoceles**
-#### What does this PR do?
- Ensure that user should get all his/her followers&following
- Fetch an article with comments

#### Description of Task to be completed
- Enable user to get all his/her followers&following
- Enable to fetch an article with comments

#### How should this be manually tested?
1. Run the following commands in Terminal
```
git clone git@github.com:andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout bg-fix-user-follow-each-others-168336607?
```
2. run `npm i` and `npm run dev`

3. Using Postman :
`POST` ; `localhost:3000/api/:username/follow`
`GET`: `localhost:3000/api/following`
`GET`: `localhost:3000/api/followers`
`POST`: `localhost:3000/api/:username/followed`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168336607](https://www.pivotaltracker.com/story/show/168336607)

#### Screenshots (if appropriate)
- following
Screen Shot 2019-09-06 at 11 34 18
- number of followers / the same to following
Screen Shot 2019-09-06 at 12 27 53
- article with comment
Screen Shot 2019-09-06 at 12 29 49

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — DISMISSED** [review]
the bug has been fixed and its ready for merge

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by Hervera — APPROVED** [review]
Thank you for inserting also the comments into the article fetch

**Review by kodek-sleuth — APPROVED** [review]
Ready for merge

**Pull request merged**
