### PR TITLE
#168559782 Fixes Notification Messages

### PR DESCRIPTION
**Pull request by elemanhillary-zz**
#### What does this PR do?
- fixes notification messages
#### Description of Task to be completed
- enable user to navigate to an article in notifications
#### How should this be manually tested?
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout bg-fix-notification-messages-168559782
npm install
npm start
```
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
[#168559782](https://www.pivotaltracker.com/story/show/168559782)
#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by niyoceles — CHANGES_REQUESTED** [review]
@elemanhillary,  you can also fix the notification link in the message sent to the user.

**Review by niyoceles — APPROVED** [review]
Bug is fixed

**Review by Hervera — DISMISSED** [review]
When a user opens one notification, the number of notifications above the notification icon in the NavBar doesn't change or decrement. You can fix that bug.

**Review by niyoceles — APPROVED** [review]

**Review by IsaiahRn — APPROVED** [review]
ready to be merged

**Review by Hervera — APPROVED** [review]
Good for this bug fix

**Pull request merged**
