### PR TITLE
#166790001 Pagination Support for Article's Ratings

### PR DESCRIPTION
**Pull request by Hervera**
#### What does this PR do?
It provides pagination support for article's ratings

#### Description of Task to be completed
- add pagination of 10 ratings per page
- add page and/or limit as query params
- add metadata on every article's ratings page

#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout  ft-paginate-articles-ratings-166790001
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgresql://dbusername:dbpassword@localhost:5432/dbname
DATABASE_TEST=postgresql://dbusername:dbpassword@localhost:5432/dbnamefortest
SECRET=whatever you want it to be
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Install and setup Postman to consume CRUD endpoints
6. Run the following requests in Postman using `localhost:3000`
## Endpoints
|  Method  |  Endpoint  |  Task  |
|  --- |  --- |  ---  |
|  `GET`  |  `/api/article/:articleSlug/ratings?page=2&limit=3`  |  `pagination support for article's ratings`  |

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166790001](https://www.pivotaltracker.com/story/show/166790001)

#### Screenshots (if appropriate)
Screen Shot 2019-07-19 at 08 06 10

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by kodek-sleuth — DISMISSED** [review]

**Review by IsaiahRn — DISMISSED** [review]
it can be merged!

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by IsaiahRn — APPROVED** [review]
ready to be merged!

**Review by niyoceles — APPROVED** [review]

**Pull request merged**
