### PR TITLE
#168341731 Fix Redirection of Share Articles on Social media and Via Email

### PR DESCRIPTION
**Pull request by Hervera**
#### What does this PR do?
Fix redirection of share articles on social media and via email

#### Description of Task to be completed
   - add frontend URL
   - add details to an email message
   - rewrite tests

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168341731](https://www.pivotaltracker.com/story/show/168341731)

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by IsaiahRn — DISMISSED** [review]
Bug was fixed and it is ready to be merged!

**Review by niyoceles — DISMISSED** [review]
A bug is fixed, It can be merged

**Review by elemanhillary-zz — APPROVED** [review]
ready to be merged

**Review by IsaiahRn — APPROVED** [review]
Bug fixed and ready for merge

**Review by niyoceles — APPROVED** [review]

**Pull request merged**
