### PR TITLE
#168243066 Fix Bug On Password Reset

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
- Ensure reset password button redirect to frontend
- Ensure user should update his phone number
#### Description of Task to be completed
- Enable link to redirect to frontend
- Enable user to update his phone number on profile
#### How should this be manually tested?
1. Run the following commands in Terminal
```
git clone git@github.com:andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout bg-fix-reset-password-168243066
```
2. run `npm run start`

3. Using Postman (or similar) send a 
`POST`: `https://ah-92explorers-api.herokuapp.com/api/password`
4. Check out your email (spam)
5. Open `reset password` button
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168243066](https://www.pivotaltracker.com/story/show/168243066)

#### Screenshots (if appropriate)
Screen Shot 2019-09-02 at 13 41 39

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by Hervera — DISMISSED** [review]
Ready to be approved

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by IsaiahRn — DISMISSED** [review]

**Review by kodek-sleuth — DISMISSED** [review]

**Review by kodek-sleuth — APPROVED** [review]

**Review by kodek-sleuth — DISMISSED** [review]

**Review by kodek-sleuth — DISMISSED** [review]

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by Hervera — DISMISSED** [review]
Ready to be merged

**Review by Hervera — APPROVED** [review]
Ready to be merged

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by kodek-sleuth — APPROVED** [review]

**Pull request merged**
