### PR TITLE
#166790013 Users Should Be Able to Report an Article

### PR DESCRIPTION
**Pull request by niyoceles**
#### What does this PR do?
Enables a user to report an article
#### Description of Task to be completed
- To set up report article functionality
- To write test
#### How should this be manually tested?
1. Run the following commands in the terminal
```
git clone https://github.com/andela/ah-92explorers-backend.git
cd ah-92explorers-backend
git checkout ft-user-report-article-166790013
npm install
npm start
```
2. Create a .env file and add the following snippets
```
DATABASE_URL=postgres://username:password@localhost:5432/authorshaven
DATABASE_=postgres://username:password@localhost:5432/authorshaven_test
```
3. Install `sequelize` globally
```
sudo npm install -g sequelize
```
4.  Create a database using `sequelize db:create`
5. Run the following requests in Postman using `localhost:3000`
- `POST`  | `/api/report/articles/:articleSlug`  |  report an article
- `GET`  |  `/api/reports/articles`  |  Admin get all reports
- `GET`  |  `/api/report/articles`  |  User get reports
- `DELETE`  |  `/api/reports/article/:articleSlug`  |  delete report an article
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166790013](https://www.pivotaltracker.com/story/show/166790013)

####Screenshots (if appropriate)
Create a report with an invalid article
Screen Shot 2019-07-28 at 12 39 23

Create report successfully
Screen Shot 2019-07-30 at 12 39 52
Screen Shot 2019-07-30 at 12 42 31

Admin get all Report
Screen Shot 2019-07-30 at 14 34 37

Admin delete report
Screen Shot 2019-07-30 at 14 35 34

Screen Shot 2019-07-30 at 12 47 35

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

### CODE REVIEW

**Review by elemanhillary-zz — CHANGES_REQUESTED** [review]
provide screen shot

**Review by IsaiahRn — CHANGES_REQUESTED** [review]
You shouldn't be returning the article's `Id` and `slug`

**Review by IsaiahRn — DISMISSED** [review]

**Review by Hervera — DISMISSED** [review]
Ready to be merged

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by elemanhillary-zz — DISMISSED** [review]
ready for merge

**Review by IsaiahRn — DISMISSED** [review]
it can be merged

**Review by Hervera — DISMISSED** [review]
Ready to be merged

**Review by Hervera — DISMISSED** [review]
Ready to be merged

**Review by elemanhillary-zz — APPROVED** [review]
ready for merge

**Review by Hervera — APPROVED** [review]
Ready to merged

**Review by IsaiahRn — APPROVED** [review]

**Pull request merged**
